#levantar (iniciar) y conectar dos contenedores de Docker: 
#uno para MySQL (la base de datos) y otro para una aplicación llamada todo-app
services:
  mysql:
    image: mysql
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_incident_app2:/var/lib/mysql
  
  incident-app:
    image: greys04/todo-app:latest
    container_name: todo-app
    ports:
      - "3007:3000"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    depends_on:
      - mysql

volumes:
  mysql_incident_app2: